# Generated by Django 5.2 on 2025-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventcomment_rating_announcement_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('ogloszenie', 'Ogłoszenie'), ('nowosc', 'Nowość'), ('wydarzenie', 'Wydarzenie'), ('informacja', 'Informacja'), ('edukacja', 'Edukacja')], default='ogloszenie', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
