# Generated by Django 5.2 on 2025-06-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_faq_contactmessage'),
        ('events', '0009_userprofile'),
    ]

    operations = [
    ]
