# Generated by Django 5.2 on 2025-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_0009_faq_contactmessage_0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wydział'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kierunek studiów'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, verbose_name='Zainteresowania'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='main_discipline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dyscyplina naukowa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='Rok studiów'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='Uczelnia'),
        ),
    ]
