# Generated by Django 5.2 on 2025-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizerrequest_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='field_of_study',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizerrequest',
            name='university',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
