# Generated by Django 5.2 on 2025-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizerrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerrequest',
            name='field_of_study',
            field=models.CharField(max_length=200, verbose_name='Rok studiów'),
        ),
        migrations.AlterField(
            model_name='organizerrequest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='organizerrequest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='organizerrequest',
            name='university',
            field=models.CharField(max_length=200, verbose_name='Uczelnia'),
        ),
    ]
