# Generated by Django 5.2 on 2025-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organizerrequest_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerrequest',
            name='field_of_study',
        ),
    ]
